services:
  portfolio:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    restart: unless-stopped
    container_name: portfolio
    ports:
      - "127.0.0.1:8000:3000"
    volumes:
      - ./logs:/app/logs
