name: Deploy to Homelab

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - "infra/Dockerfile"
      - "infra/docker-compose.yaml"
      - "infra/.dockerignore"
      - "package.json"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-homelab:
    name: Deploy to Homelab Server
    runs-on: self-hosted

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Stop and Remove Existing Containers
        run: docker-compose -f infra/docker-compose.yaml down

      - name: Build and Start Containers
        run: docker-compose -f infra/docker-compose.yaml up -d --build
